#!/bin/bash
RED=$'\e[1;31m'
GREEN=$'\e[1;32m'
WHITE=$'\e[1;37m'
NC=$'\033[0m'
git add --ignore-removal .
echo "${GREEN}Modified files successfully added${NC}"
while true; do
    read -p "${WHITE}Do you want to commit your changes ? [Yy] or [Nn] : " yn
    case $yn in
        [Yy]* ) read -p "Enter your commit message: ${NC}" msg
                git commit -m "[ADD] :rocket: --> $msg"; break;;
        [Nn]* ) echo "${RED}No message entered"; exit;;
        * ) echo "${RED}No message entered"; exit;;
    esac
done
while true; do
    read -p "${WHITE}Do you want to push your changes ? [Yy] or [Nn] : ${NC}" yn
    case $yn in
        [Yy]* ) echo "${GREEN}"
                git push; break;;
        [Nn]* ) echo "${RED}Commit(s) not pushed"; exit;;
        * ) echo "${RED}Commit(s) not pushed"; exit;;
    esac
done
exit
